

// BUYER
export const GET_BUYERS = 'GET_BUYERS';

// AREA
export const GET_AREAS = 'GET_AREAS';

// DEFECT
export const GET_DEFECTS = 'GET_DEFECTS';

// AUTH
export const AUTH_SIGNIN = 'AUTH_SIGNIN';
export const AUTH_CHANGE_PASSWORD = 'AUTH_CHANGE_PASSWORD';
export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// MATERIAL
export const GET_MATERIALS = 'GET_MATERIALS';

// INSPECTION
export const GET_INSPECTIONS = 'GET_INSPECTIONS';
export const GET_INSPECTIONS_BY_SEARCH = 'GET_INSPECTIONS_BY_SEARCH';
export const CREATE_INSPECTION = 'CREATE_INSPECTION';
export const GET_INSPECTION_BY_ID = 'GET_INSPECTION_BY_ID';
export const EDIT_INSPECTION ='EDIT_INSPECTION';
export const GET_EXPORT_REPORT_LIST = 'GET_EXPORT_REPORT_LIST';

// SUPPLIER
export const GET_SUPPLIERS = 'GET_SUPPLIERS';

// ITEM
export const FIND_ITEMS = 'FIND_ITEMS';
export const GET_ITEM_BY_ID = 'GET_ITEM_BY_ID';
export const GET_ITEMS = 'GET_ITEMS'

// DEFECT DATA
export const CREATE_DEFECT_DATA = 'CREATE_DEFECT_DATA';
export const GET_DEFECT_DATAS = 'GET_DEFECT_DATAS';


//LOADING
export const SET_MESSAGE_NULL = 'SET_MESSAGE_NULL';
export const START_LOADING_HOME = 'START_LOADING_HOME';
export const END_LOADING_HOME = 'END_LOADING_HOME';