

// BUYER
export const GET_BUYERS = 'GET_BUYERS';


// AUTH
export const AUTH_SIGNIN = 'AUTH_SIGNIN';
export const AUTH_CHANGE_PASSWORD = 'AUTH_CHANGE_PASSWORD';
export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// MATERIAL
export const GET_MATERIALS = 'GET_MATERIALS';

// MOLD MATERIAL
export const GET_MOLD_MATERIALS = 'GET_MOLD_MATERIALS';

// SUPPLIER
export const GET_SUPPLIERS = 'GET_SUPPLIERS';

// ITEM
export const CREATE_ITEM = 'CREATE_ITEM';
export const CLEAR_ITEM_TABLE = 'CLEAR_ITEM_TABLE';
export const GET_ITEMS = 'GET_ITEMS'
export const EDIT_ITEM = 'EDIT_ITEM'
export const SET_MESSAGE_NULL = 'SET_MESSAGE_NULL';
export const GET_ITEMS_BY_SEARCH = 'GET_ITEMS_BY_SEARCH';

// MOLD
export const CREATE_MOLD = 'CREATE_MOLD';
export const FIND_MOLD = 'FIND_MOLD';
export const GET_MOLDS_BY_ITEM_ID = 'GET_MOLDS_BY_ITEM_ID';
export const EDIT_MOLD_WITH_ID = 'EDIT_MOLD_WITH_ID';
export const EXPORT_REPORT = 'EXPORT_REPORT';
export const CLEAR_MOLD_STATE = 'CLEAR_MOLD_STATE';
export const COUNT_NEAR_VALIDATION = 'COUNT_NEAR_VALIDATION';

// DELIVERY
export const DELETE_DELIVERIES_BY_MOLD_ID = 'DELETE_DELIVERIES_BY_MOLD_ID';
export const ADD_DELIVERY = 'ADD_DELIVERY';
export const EDIT_DELIVERY = 'EDIT_DELIVERY';
export const GET_DELIVERIES_BY_MOLD_ID = 'GET_DELIVERIES_BY_MOLD_ID';
export const EDIT_DELIVERY_WITH_ID = 'EDIT_DELIVERY_WITH_ID';
export const FIND_PO = 'FIND_PO';
 

//LOADING
export const START_LOADING_HOME = 'START_LOADING_HOME';
export const END_LOADING_HOME = 'END_LOADING_HOME';